"""One-shot DocAtlas installer: pick a data location, install the Skill,
register the MCP server, and verify itself when done.

    python install.py                      # everything, data in <repo>/data
    python install.py --data-dir D:/Docs    # data elsewhere (program and data
                                            # need not live together)
    python install.py --print               # print the MCP snippet only
    python install.py --skip-skill          # register MCP only
    python install.py --skip-mcp            # install the Skill only

Written in Python rather than as .ps1/.sh: DocAtlas needs Python to run at all,
so using it for the installer is cross-platform for free, with no per-OS copy
to keep in step.

Two rules:

1. **Verify before writing config.** Before registering anything, start the MCP
   server for real from an unfamiliar directory and complete the handshake. If
   that fails, nothing is written — half-written config is harder to diagnose
   than no install at all.
2. **Never rewrite someone else's config.** Claude Code goes through the
   official `claude mcp add`; Codex is only **appended** to when the entry is
   absent; every other client just gets the snippet printed. Parsing and
   rewriting a config of thousands of lines loses fidelity, which is not worth
   risking to save one paste.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
LAUNCHER = REPO_ROOT / "mcp_server.py"
SERVER_NAME = "docatlas"
SKILL_NAME = "docatlas"
MIN_PYTHON = (3, 11)

# Skills install to <home>/<client>/skills/<skill>/. Add a client with a line.
SKILL_CLIENTS = {
    "claude-code": Path.home() / ".claude",
    "codex": Path.home() / ".codex",
}


class Failed(Exception):
    """Installation failed, with a sentence a human can act on."""


# --------------------------------------------------------------------------
# Data location
# --------------------------------------------------------------------------


def save_choices(data_dir: str | None, dataset: str | None) -> tuple[Path, str | None]:
    """Record where the data lives and which library is the default, in
    `.docatlas-local.toml`.

    It has to be a file: an MCP client starting a subprocess does not carry the
    environment variables of your shell, so with `DOCATLAS_HOME` /
    `DOCATLAS_DATASET` alone the library the command line finds would be
    invisible to MCP.

    Anything not passed is left as it was, never wiped by this run.
    """
    from docatlas.runtime import LOCAL_SETTINGS, available_dataset_ids, local_settings

    settings = local_settings()
    default_dir = REPO_ROOT / "data"
    if data_dir:
        target = Path(data_dir).expanduser().resolve()
        settings["home"] = str(target)
    else:
        target = Path(settings.get("home") or default_dir).resolve()
    target.mkdir(parents=True, exist_ok=True)
    if target == default_dir.resolve():
        settings.pop("home", None)

    if dataset:
        if dataset not in (available := available_dataset_ids()):
            raise Failed(f"No such dataset: {dataset}. Available: {', '.join(available)}")
        settings["dataset"] = dataset

    if settings:
        LOCAL_SETTINGS.write_text(
            "# Generated by install.py. One per machine, never committed.\n"
            + "".join(f"{key} = {json.dumps(str(value))}\n"
                      for key, value in sorted(settings.items())),
            encoding="utf-8",
        )
    else:
        LOCAL_SETTINGS.unlink(missing_ok=True)
    return target, settings.get("dataset")


# --------------------------------------------------------------------------
# MCP
# --------------------------------------------------------------------------


def mcp_config(python: str) -> dict:
    """The one stdio configuration every client gets.

    **No `cwd`.** DocAtlas is a plain folder rather than a package installed
    into a Python environment, so `python -m docatlas mcp` only resolves inside
    the repository — and `cwd` is a field each client decides for itself
    whether to support. Where it is unsupported it fails silently, leaving
    nothing but `No module named docatlas`. Going through `mcp_server.py`
    depends on nobody: Python puts the script's own directory on `sys.path`, so
    it works from any working directory.

    `command` is an absolute path: the PATH a client gives a subprocess is not
    necessarily the one in your shell.
    """
    return {"command": python, "args": [str(LAUNCHER)]}


def verify_handshake(python: str) -> str:
    """Start a real process from an unfamiliar directory, without PYTHONPATH,
    and complete initialize.

    Exit code 0 proves nothing about the server being alive — what it replied
    is what counts.
    """
    env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
    env["PYTHONIOENCODING"] = "utf-8"
    request = json.dumps({
        "jsonrpc": "2.0", "id": 1, "method": "initialize",
        "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                   "clientInfo": {"name": "install", "version": "1"}},
    })
    proc = subprocess.run(
        [python, str(LAUNCHER)],
        input=request + "\n", cwd=Path.home(), env=env,
        capture_output=True, text=True, encoding="utf-8", timeout=120,
    )
    reply = (proc.stdout or "").strip().splitlines()
    if not reply:
        raise Failed(f"The MCP server did not answer initialize.\n{proc.stderr.strip()[:600]}")
    name = json.loads(reply[0]).get("result", {}).get("serverInfo", {}).get("name")
    if not name:
        raise Failed(f"The initialize reply carries no serverInfo: {reply[0][:300]}")
    return name


def register_claude_code(python: str) -> str | None:
    claude = shutil.which("claude")
    if not claude:
        return None
    # Let the official command write it; ~/.claude.json holds other state too.
    subprocess.run([claude, "mcp", "remove", SERVER_NAME, "-s", "user"],
                   capture_output=True, text=True)
    done = subprocess.run(
        [claude, "mcp", "add", SERVER_NAME, "-s", "user", "--", python, str(LAUNCHER)],
        capture_output=True, text=True,
    )
    if done.returncode != 0:
        raise Failed(f"claude mcp add failed: {done.stderr.strip()[:300]}")
    return "claude-code"


def register_codex(python: str) -> str | None:
    """Codex uses TOML. Appended only when the entry is absent; otherwise the
    user edits it themselves.

    There is no third-party TOML writer here, and rewriting the whole file
    would lose comments and formatting. Appending a second section with a name
    that already exists would make Codex fail to parse it outright — that is
    breaking the user's config, not installing.
    """
    config = Path.home() / ".codex" / "config.toml"
    if not config.parent.exists():
        return None
    text = config.read_text(encoding="utf-8") if config.exists() else ""
    section = f"[mcp_servers.{SERVER_NAME}]"
    block = (
        f"\n{section}\n"
        f"command = {json.dumps(python)}\n"
        f"args = [{json.dumps(str(LAUNCHER))}]\n"
    )
    if section in text:
        print(f"  codex: {section} already present, left alone. To move to the new form, replace it by hand with:")
        print("".join(f"    {line}\n" for line in block.strip().splitlines()))
        return None
    with config.open("a", encoding="utf-8") as handle:
        handle.write(block)
    return "codex"


# --------------------------------------------------------------------------
# Skill
# --------------------------------------------------------------------------


def render_skill() -> dict[str, str]:
    """Fill the placeholders in skills/docatlas/*.md for the current dataset.

    The filling is done by `docatlas.cli`, the only part that knows datasets.
    This function only puts the files in the right place.
    """
    from docatlas.cli import skill_substitutions

    source = REPO_ROOT / "skills" / SKILL_NAME
    if not (source / "SKILL.md").exists():
        raise Failed(f"Skill source not found: {source / 'SKILL.md'}")
    substitutions = skill_substitutions()
    rendered = {}
    for path in sorted(source.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        for name, value in substitutions.items():
            text = text.replace("{{" + name + "}}", value)
        if leftover := sorted(set(re.findall(r"\{\{([A-Z_]+)\}\}", text))):
            raise Failed(f"{path.name} has placeholders nobody knows: {', '.join(leftover)}")
        rendered[path.name] = text
    return rendered


def install_skill(rendered: dict[str, str]) -> list[str]:
    done = []
    for client, home in SKILL_CLIENTS.items():
        # Only clients that actually exist: conjuring a directory just leaves
        # files nobody reads.
        if not home.exists():
            continue
        target = home / "skills" / SKILL_NAME
        target.mkdir(parents=True, exist_ok=True)
        for name, text in rendered.items():
            # Always UTF-8 without BOM: a BOM stops Codex recognising the
            # frontmatter of SKILL.md.
            (target / name).write_bytes(text.encode("utf-8"))
        verify_skill(target, rendered)
        done.append(f"{client} → {target}")
    return done


def verify_skill(target: Path, rendered: dict[str, str]) -> None:
    """Check the install. "The command exited cleanly" is not the same as the
    client recognising the skill."""
    for name in rendered:
        raw = (target / name).read_bytes()
        if len(raw) < 3:
            raise Failed(f"{target / name} was written empty")
        if raw[:3] == b"\xef\xbb\xbf":
            raise Failed(f"{target / name} has a BOM, which Codex will not recognise")
    if not (target / "SKILL.md").read_text(encoding="utf-8").startswith("---"):
        raise Failed("SKILL.md does not start with frontmatter; no client will treat it as a skill")


# --------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Install the DocAtlas Skill and MCP server",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--data-dir", help="where the data goes (default <repo>/data)")
    parser.add_argument("--dataset", help="default library (otherwise chosen per command)")
    parser.add_argument("--print", dest="print_only", action="store_true",
                        help="print the MCP snippet only, touch no files")
    parser.add_argument("--skip-mcp", action="store_true", help="do not register MCP")
    parser.add_argument("--skip-skill", action="store_true", help="do not install the Skill")
    args = parser.parse_args(argv)

    if sys.version_info < MIN_PYTHON:
        version = ".".join(map(str, MIN_PYTHON))
        print(f"Python {version}+ required, this is {sys.version.split()[0]}", file=sys.stderr)
        return 1
    if not LAUNCHER.exists():
        print(f"MCP entry point not found: {LAUNCHER}", file=sys.stderr)
        return 1

    # The interpreter **running this installer**, not whatever PATH turns up:
    # the one that can run the install is the one that can run DocAtlas.
    python = sys.executable
    snippet = json.dumps({"mcpServers": {SERVER_NAME: mcp_config(python)}}, indent=2)
    if args.print_only:
        print(snippet)
        return 0

    try:
        data_dir, dataset = save_choices(args.data_dir, args.dataset)
        print(f"Program: {REPO_ROOT}")
        print(f"Data:    {data_dir}")
        print(f"Default library: {dataset or 'none (choose per command, or set --dataset)'}")
        print(f"Python:  {python}\n")

        if not args.skip_mcp:
            print(f"✓ MCP handshake passed: {verify_handshake(python)}"
                  f" (started from {Path.home()}, no PYTHONPATH)")
            registered = [name for name in
                          (register_claude_code(python), register_codex(python)) if name]
            if registered:
                print(f"✓ MCP registered: {', '.join(registered)} (effective after a client restart)")
            else:
                print("  No client could be registered automatically.")
            print("\nFor other clients (Claude Desktop / Cursor / Cline…), paste this into the config:")
            print(snippet)

        if not args.skip_skill:
            from docatlas.runtime import DatasetNotChosen

            try:
                installed = install_skill(render_skill())
                if installed:
                    print("\n✓ Skill installed:")
                    for line in installed:
                        print(f"    {line}")
                else:
                    print(f"\n  No client supporting skills was found"
                          f" (looked for: {', '.join(SKILL_CLIENTS)}).")
            except DatasetNotChosen:
                # Unlike MCP, the Skill document says things like "the current
                # default library is X", so one has to be chosen. Reached when
                # this machine has more than one dataset and no default. Not a
                # fault: pick one, or build a library first, then rerun.
                print(
                    "\n  Skipping the Skill: this machine has more than one dataset "
                    "and no default yet.\n"
                    "  Run `python install.py --dataset <id>` to settle it, or build "
                    "a library first, then rerun this script."
                )
    except Failed as error:
        print(f"\nInstall failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
